[package]
name = "jj-core"
description = "Core types and algorithms for Jujutsu - an experimental version control system"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true

[[bench]]
name = "diff_bench"
harness = false

[dependencies]
blake2 = { workspace = true }
bstr = { workspace = true }
digest = { workspace = true }
either = { workspace = true }
etcetera = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
hashbrown = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jj-core-proc-macros = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ignore = "0.4.25"

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
eyre = { workspace = true }
insta = { workspace = true }
maplit = { workspace = true }
pollster = { workspace = true }
sapling-renderdag = { workspace = true }
test-case = { workspace = true }

[target.'cfg(windows)'.dependencies]
same-file = { workspace = true }
winreg = { workspace = true }

[lints]
workspace = true
